[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aoc-2022-00"

[[bin]]
name = "aoc-2022-01"

[[bin]]
name = "aoc-2022-02"

[[bin]]
name = "aoc-2022-03"

[dependencies]
anyhow = "1.0.65"
